// Generated by dts-bundle v0.7.3
// Dependencies for this module:
//   ../history
//   ../react

declare module 'react-history-switch' {
    import Switch from "react-history-switch/lib/Switch";
    export { Switch };
    export * as history from 'history';
    import ISwitchItemInternal from "react-history-switch/model/ISwitchItem";
    import ISwitchStateInternal from "react-history-switch/model/ISwitchState";
    export type ISwitchItem = ISwitchItemInternal;
    export type ISwitchState = ISwitchStateInternal;
}

declare module 'react-history-switch/lib/Switch' {
    import ISwitchProps from 'react-history-switch/model/ISwitchProps';
    export const Switch: ({ items, history, NotFound, }: ISwitchProps) => import("react").ReactElement<any, string | ((props: any) => import("react").ReactElement<any, any> | null) | (new (props: any) => import("react").Component<any, any, any>)>;
    export default Switch;
}

declare module 'react-history-switch/model/ISwitchItem' {
    export interface ISwitchItem {
        path: string;
        component?: React.ComponentType<any>;
        guard?: () => boolean;
        redirect?: string;
    }
    export default ISwitchItem;
}

declare module 'react-history-switch/model/ISwitchState' {
    export interface ISwitchState {
        component: React.ComponentType<any>;
        redirect?: string;
        params: Record<string, unknown>;
        key: string;
    }
    export default ISwitchState;
}

declare module 'react-history-switch/model/ISwitchProps' {
    import { BrowserHistory } from "history";
    import { ComponentType } from "react";
    import ISwitchItem from "react-history-switch/model/ISwitchItem";
    export interface ISwitchProps {
        items: ISwitchItem[];
        history?: BrowserHistory;
        NotFound?: ComponentType;
    }
    export default ISwitchProps;
}

