// Generated by dts-bundle v0.7.3
// Dependencies for this module:
//   ../history
//   ../react

declare module 'react-history-switch' {
    import Switch from 'react-history-switch/lib/Switch';
    import ISwitchItemInternal from 'react-history-switch/model/ISwitchItem';
    export { Switch };
    export * as history from 'history';
    export type ISwitchItem = ISwitchItemInternal;
}

declare module 'react-history-switch/lib/Switch' {
    import React from 'react';
    import { BrowserHistory, HashHistory, MemoryHistory } from 'history';
    export interface ISwitchItem {
        path: string;
        element?: React.ComponentType<any>;
        guard?: () => boolean | Promise<boolean>;
        prefetch?: (params: Record<string, any>) => Record<string, any> | Promise<Record<string, any>>;
        unload?: (params: Record<string, any>) => Promise<void> | void;
        redirect?: string | ((params: Record<string, any>) => string | null);
    }
    export interface ISwitchProps {
        items: ISwitchItem[];
        fallback?: (e: Error) => void;
        history?: BrowserHistory | MemoryHistory | HashHistory;
        Forbidden?: React.ComponentType<any>;
        NotFound?: React.ComponentType<any>;
        Loader?: React.ComponentType<any>;
        Error?: React.ComponentType<any>;
        onLoadStart?: () => void;
        onLoadEnd?: (isOk?: boolean) => void;
        throwError?: boolean;
    }
    export const Switch: ({ Loader, Forbidden, NotFound, Error, history, fallback, items, onLoadStart, onLoadEnd, throwError }: ISwitchProps) => JSX.Element;
    export default Switch;
}

declare module 'react-history-switch/model/ISwitchItem' {
    export interface ISwitchItem {
        path: string;
        element?: React.ComponentType<any>;
        guard?: () => boolean | Promise<boolean>;
        prefetch?: (params: Record<string, any>) => Record<string, any> | Promise<Record<string, any>>;
        unload?: (params: Record<string, any>) => Promise<void> | void;
        redirect?: string | ((params: Record<string, any>) => string | null);
    }
    export default ISwitchItem;
}

